# Quantitative Trading Platform Configuration

# Model Configuration
models:
  monte_carlo:
    num_simulations: 10000
    confidence_level: 0.95
    
  ml_models:
    - random_forest
    - xgboost
    - gradient_boosting
    - ensemble
    
  forecast_horizons: [1, 5, 21, 63, 126, 252, 1260]  # days
  
  arima:
    max_p: 3
    max_d: 2
    max_q: 3

# Risk Management
risk:
  max_position_size: 0.05      # 5% max position size
  max_portfolio_var: 0.02      # 2% daily VaR limit
  max_drawdown: 0.15           # 15% max drawdown
  max_concentration: 0.25      # 25% max sector concentration
  risk_free_rate: 0.02         # 2% risk-free rate
  max_beta: 1.5               # Maximum portfolio beta
  
  # Stress test scenarios
  stress_scenarios:
    market_crash:
      description: "2008-style market crash"
      equity_decline: -0.40
      volatility_spike: 3.0
      
    sector_rotation:
      description: "Major sector rotation"
      tech_decline: -0.20
      value_increase: 0.10
      
    interest_rate_shock:
      description: "Rapid interest rate increase"
      rate_increase: 0.02
      growth_impact: -0.15

# Trading Configuration
trading:
  min_confidence: 0.60         # Minimum forecast confidence
  min_expected_return: 0.05    # 5% minimum expected return
  max_correlation: 0.80        # Maximum correlation between positions
  
  # Position sizing
  kelly_fraction_cap: 0.25     # Cap Kelly fraction at 25%
  min_position_size: 0.01      # 1% minimum position
  max_position_size: 0.10      # 10% maximum position
  
  # Option trading
  options:
    max_time_to_expiry: 60     # Maximum 60 days to expiration
    min_time_to_expiry: 7      # Minimum 7 days to expiration
    max_iv_percentile: 80      # Maximum IV percentile
    min_open_interest: 100     # Minimum open interest

# Data Sources
data:
  primary_source: "yfinance"
  backup_sources: ["alpha_vantage", "quandl"]
  
  # Update frequencies
  intraday_update: 300         # 5 minutes
  daily_update: "16:30"        # After market close
  
  # Data validation
  max_missing_days: 5          # Maximum consecutive missing days
  min_history_days: 252        # Minimum 1 year of history

# Feature Engineering
features:
  technical_indicators:
    - sma: [5, 10, 20, 50, 200]
    - ema: [12, 26]
    - rsi: [14]
    - macd: [12, 26, 9]
    - bollinger_bands: [20, 2]
    - stochastic: [14, 3]
    
  fundamental_ratios:
    - pe_ratio
    - pb_ratio
    - debt_to_equity
    - roe
    - roa
    
  market_regime:
    - volatility_regime
    - trend_regime
    - correlation_regime
    
  time_features:
    - day_of_week
    - month_of_year
    - quarter
    - earnings_proximity

# Reporting
reporting:
  output_formats: ["json", "csv", "pdf"]
  include_charts: true
  chart_types: ["price", "forecast", "risk"]
  
  # Email notifications
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    recipients: []
    
  # Slack notifications
  slack:
    enabled: false
    webhook_url: ""
    channel: "#trading-alerts"

# Performance Monitoring
monitoring:
  track_predictions: true
  backtest_period: 252         # 1 year backtest
  benchmark: "SPY"
  
  # Performance metrics
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - calmar_ratio

# Logging
logging:
  level: "INFO"
  file: "logs/trading_engine.log"
  max_size: "10MB"
  backup_count: 5
  
  # Log components
  components:
    data_ingestion: true
    feature_engineering: true
    model_training: true
    forecasting: true
    trade_generation: true
    risk_management: true
